---
title: "RaceId2/StemID Post-Analysis"
author: "Jasper Koning & Michael de Kok"
---



## Highlight transcirpt counts of a set of genes in t-SNE map

```{r Genes, include=TRUE}

# g <- c("Apoa1__chr9", "Apoa1bp__chr3", "Apoa2__chr1", "Apoa4__chr9", "Apoa5__chr9")
# plotexptsne(sc,g,n="Apoa genes",logsc=TRUE)

```



## Analysis of Differentially expressed genes between two sets of clusters

```{r DiffClusters, include=TRUE}

#d <- diffgenes(sc,cl1=1,cl2=c(2,3),mincount=5)
#plotdiffgenes(d,gene=names(d$z)[1])

```



## Analysis of Specific Clusters

```{r ClusterAnalysis, include=TRUE}

## extract projections onto all links for all cells in a given cluster i

#x <- getproj(ltr,i=1)

## heatmap of all projections for cluster i

#pheatmap(x$pr)

## heatmap of z-score for all projections for cluster i

#pheatmap(x$prz)

```



## Analysis of Branch Cells 

```{r BranchCells, include=TRUE}

## extracting all cells on two branches sharing the same cluster and computing differentially expressed genes between these two branches

#x <- branchcells(ltr,list("1.3","1.2"))

## z-scores for differentially expressed genes

#head(x$diffgenes$z)

## plotting the cells on the two branches as additional clusters in the t-SNE map

#plottsne(x$scl)

```

