# This file should contain everything to configure the workflow on a global 
# scale. 

# NOTE: It is advisable that you copy, move and configure this file to and for 
# each experimental data repository.

################################################################################
#                                                                              #
#                      Data directories, file paths                            #
#                                                                              #
################################################################################

#####   TOP DATA DIRECTORY  #####

# The location of the top level data directory.
# All subsequent paths should be given relative to this path!
datadir: O:/m.kok2/PROJECTS/SCRNASEQ/Snakemake Analyzed Datasets

#####   REFERENCE GENOMES   #####

# Main directory with reference genomes (<datadir>/<refdir>)
# Reference genomes and their gtf files should be stored in subdirectories of
# this directory with name <reference>, where <reference> is for example 
# "mouse-grcm38". The variable <reference> is the same as the one in the
# "reference" column of the "references" file (see below).
refdir: reference-sequences/genomes

# The STAR index main directory (<datadir>/<indexdir>)
# Index files will be stored in subdirectories with name <reference>, see below. 
indexdir: reference-sequences/indexed-genomes

# The reference genome, see the <references> file for valid entries. A 
# <reference> folder is expected to be a subfolder of <datadir>/<refdir>, 
# and to contain a gzipped reference genome file and a corresponding gtf file.
# The star-index workflow will create a folder <datadir>/<indexdir>/<reference>
# with the genome index files.
reference: mouse-grcm38

#####   EXPERIMENTAL DATA   #####

# The local data repository relevant for the analyzed experiment. If following 
# the advice at the head of this file, this would be the path to the directory 
# where this config file resides (<datadir><repo>).
repo: research-sbi-mouse-lymph-node-stromal-cell-time-series

# NOTE: All following directories are subdirectories of the <datadir><repo>
# directory.

# Directory name where large temporary files will be stored 
# (Full path: <datadir>/<repo>/<tmpstore>).
tmpstore: snakemake_temporary_files
# Directory where output files will be stored
# (Full path: <datadir>/<repo>/<output>)
output: snakemake_output
# Directory with sequence files
# (Full path: <datadir>/<repo>/<sequences>)
sequences: sequences_2018_Aug

# The following files are expected to be located in subdirectories of the
# <repo> directory 

# File with experimental sample annotations (<datadir>/<repo>/<samples>)
samples: annotations_2018_Aug/annotations.tsv
# File with experimental reference genome annotations
# (Ful path: <datadir>/<repo>/<references>)
references: annotations_2018_Aug/reference.tsv
# File with known cell barcodes
# (Full path: <datadir>/<repo>/<celbc>)
celbc: annotations_common/celseq_barcodes.192.txt

#####   FILE SUFFIX ENCODING   #####

# The file suffix encodes which files contain sequences and code counts.
# The complete file name is reconstructed as {fileprefix}{filesuffix}
filesuffix:
  align:
    - _R2.fastq.gz
  barcodes:
    - _R1.fastq.gz


#####   TEST RUN SAMPLES   #####

# Whether this is a test run. This limits the amounts of samples used to speed 
# up testing.
istest: false
# Samples for test runs. The names must be taken from the 'fileprefix' column in
# the 'samples' file 
testset:
  - LNS2_1
  - LNS_W0_P2_7


#####   PACKAGES   #####
# TODO: move location/installation of packages to R-scripts that use them

# Folder(s) with R packages
rpackagesfolders: 
  - C:/Users/Mike/Documents/R/win-library/3.6
  - C:/Program Files/R/R-3.6.0/library


################################################################################
#                                                                              #
#                            Parameter settings                                #
#                                                                              #
################################################################################


#####   SHELL PARAMETERS FOR MODULES 1-3   #####

params:
  # Module 1 - STAR Index
  starindex:
    # Indexing requires a large amount of memory. Indexing a mouse genome 
    # requires ~31 G memory. Additional threads don't seem to consume much more
    # memory but do speed up the process a lot. The 'extra' parameter settings
    # reported below affect memory consumption and speed.
    #
    # NOTE: We tested indexing of mouse gemome on a machine with 8 cores and
    # 39.2 G memory. Using STAR 2.6.0a and 8 threads (snakemake -j 8)
    # computation time was ~ 0.5 hr. We used the following parameters (default
    # values):
    #   - sjdbOverhang 100
    #   - genomeChrBinNbits 18
    #   - genomeSuffixLengthMax -1
    gtf:
      # For GTF files (Eukaryotes)
      - "--sjdbOverhang 100" # the default value
      - "--genomeChrBinNbits 18" # the default value 
      - "--genomeSuffixLengthMax -1" # the default value 
    gff:
      # For Bacterial Genomes having GFF-3 Format Genome Annotation Files. Check
      # whether CDS and Exon are features in the GFF File.
      - "--sjdbGTFfeatureExon CDS" 
      - "--sjdbGTFtagExonParentTranscript gene"
      # You should also adapt these, please see the STAR manual for best values
        # - "--genomeSAindexNbases 14"
        # - "--genomeChrBinNbits 14"

  # Module 2 - STAR Align
  star:
    # Keep the STAR index in memory for the next aligment run. This saves time
    # because loading a mouse genome index takes approximately 5 minutes.
    - "--genomeLoad LoadAndKeep"
      
  # Module 4 - Mapping Barcodes
  # Extra Parameters for the featureCounts Package
  featureCounts:
    - '-F GTF'
    - '-g gene_id'
    - '-t exon'
    - '--primary'

  # Module 3 - Parsing of barcodes
  barcoding:
    cell_bc_start:
      index: 1
      from_end: FALSE
    cell_bc_end:     
      index: 12
      from_end: FALSE
    
    umi_start: 
      index: 13
      from_end: FALSE
    umi_end: 
      index: 20
      from_end: FALSE

#####   QUALITY CONTROL   #####

# The variable by which data should be grouped when performing quality control.
# Quality checks will be performed per group. This variable must be the name of
# a column in the <samples> file. If no grouping is needed then the value of
# this parameter should be set to "null" or "~", i.e. the line should read
# QCgrouping: null OR QCgrouping: ~
# TODO: test null value of QCgrouping
QCgrouping: experiment

#####   DATA ANALYSIS   #####

# What column of the experimental "samples" annotations file defines the 
# different samples. These will have their count tables kept seperate on top of 
# all being combined. If no split is necessary, input FALSE.
# TODO: Change 'FALSE' input to canonical "null" or "~", see above.
samplescolumn: time

# The Kind of Annotation format that is used (gtf for Eukaryotes, gff for 
# Bacterial Genomes having GFF-3 Format Genome Annotation File, refers to 
# Entries in params:starindex)
annotationformat: gtf

# Folder with conversion ID's between ENSEMBL and other custom formats that will
# be added in the output.
# NOTE: See example for MMusculus. Should a new table be made for any other 
# model, edit and use the following script: 
# '/scripts/annotation-conversion-lookup-table-generator.R'
conversiontables: reference-sequences/gene-conversion-tables


#### Parameters for correction of UMI counts
# To infer the number of transcripts of a gene, a correction on the number of 
# observed UMI's per gene can be made that accounts for the possibility that the
# same UMI is attached to different RNA molecules of the same gene. See eq. 3 in
# Grun et al. (2014), Nature Methods 11:637--640 
# http://dx.doi.org/10.1038/nmeth.2930

# Do you want to apply this correction?
UMIcorrection: true

# The theoretical number of UMIs, usually 4^n where n is the length of the UMI 
# barcode (UMIcardinality is the same as 'K' in eq. 3)
UMIcardinality: 65536
