# testing hooks
from snakemake.shell import shell

configfile: "config.yaml"

rule all:
    input: 'fileb.txt'
    run:
        print('touch ' + config['reference']['index'])

rule a:
    input: 'filea.txt'
    output: 'fileb.txt'
    shell: 'echo fileb.txt'

onstart:
    print('Making filec.txt')
    shell('echo ' + config['reference']['index'])

onsuccess:
    print('Removing the genome index file from memory becuase of successful termination')

onerror:
    print('Removing the genome index file from memory because of error')