# testing hooks
from snakemake.shell import shell

configfile: "config.yaml"

rule all:
    input: 'fileb.txt'
    run:
        print('touch ' + config['reference']['index'])

rule a:
    input: 'filea.txt'
    output: 'fileb.txt'
    shell: 'touch fileb.txt'

onstart:
    print('Making filec.txt')
    shell('echo ' + config['reference']['index'])

onsuccess:
    print('Stopping because Succes')

onerror:
    print('Stopping because Error')