# Snakemake Workflow for Module 4: When multiple plates are present, combining all plate count tables into a single normalized count table

# Include common settings
include: "../../common.snakefile"

rule all:
    input:
        combinedplates = expand('{outputpath}/count_tables/ALL.csv', outputpath = outputpath)

rule combine_plates:
    input:
        plates = expand('{tmppath}/mapping/{reference}/{fileprefix}/counts.tsv', tmppath = tmppath, reference = config['reference'], fileprefix=fileprefixes),
        inputfolder = expand('{tmppath}/mapping/{reference}', tmppath = tmppath, reference = config['reference']),
        annotations = annotationfile,
        conversiontable = conversionfolder
    output:
        expand('{outputpath}/count_tables/ALL.csv', outputpath = outputpath)
    params:
        outputfolder = expand('{outputpath}/count_tables', outputpath = outputpath),
        rpackagesfolders = rpackagesfolders,
        samples = fileprefixes,
        samplescolumn = samplescolumn
    script:
        'scripts/combinespreadplates.R'
