# Snakemake Workflow for Module 5: Running RaceID / StemID on combined count tables

# Include common settings
include: "../common.snakefile"

# Pseudorule consuming all the Final Output
rule all:
    input:
        stemraceidreport    = '{raceidoutputsbydate}/RaceID3_StemID2_sample.html',
        clustercells        = '{raceidoutputsbydate}/cell_clust.xls',
        clustergenes        = '{raceidoutputsbydate}/cell_clust_diff_genes_cl_*'

rule    :
    input:
        countscombined      = expand('{output}/combined_count_tables/counttables_combined_ALL.csv', output = output),
        conversionfolder    = conversionfolder
    output:
        stemraceidreport    = '{raceidoutputsbydate}/RaceID3_StemID2_sample.html',
        clustercells        = '{raceidoutputsbydate}/cell_clust.xls'
    params:
        outputdirectory     = '{raceidoutputsbydate}',
        rpackagesfolders    = rpackagesfolders,
        mintotal            = mintotal,
        minexpr             = minexpr,
        minnumber           = minnumber,
        LBatch              = LBatch,
        CGenes              = CGenes,
        FGenes              = FGenes,
        ccor                = ccor,
        maxclustnr          = maxclustnr,
        bootnr              = bootnr,
        RunStemID           = RunStemID,
        pdishuf             = pdishuf,
        scthr               = scthr
    script:
        'scripts/RaceID3_StemID2_render.R'

# Copy config used to output folder
rule outputconfig:
    shell:
        'cat > {raceidoutputsbydate}/snakemake_config_used.yml'
configfilelines = open(config_file).read()
os.mkdir(raceidoutputsbydate)
configused = open(raceidoutputsbydate +'/snakemake_config_used.yml',"w+")
configused.write(configfilelines)