# Snakemake Workflow for Module 6: Running RaceID / StemID on normalized combined count tables

# Include common settings
include: "../common.snakefile"

rule combine-plates:
    input:
        '{tmpstore}/combine_plates/{reference}/{fileprefix}/counts_combined.tsv'
    output:
        'RaceID2_StemID_sample.Rmd'
        # Cluter Tables
    script:
        'RaceID2_StemID_sample.R'