# Snakemake Workflow for Module 5: When multiple plates are present, combining all plate count tables into a single normalized count table

# Include common settings
include: "../common.snakefile"

rule all:
    input:
        output = expand('{output}/counttables_combined_ALL.tsv', output = output)
rule combine-plates:
    input:
        plates              = expand('{tmpstore}/mapping/{fileprefix}/counts.tsv', tmpstore=tmpstore, fileprefix=samples['fileprefix'])
        inputfolder         = expand('{tmpstore}/mapping/', tmpstore=tmpstore)
        annotations         = annotationfile
        conversiontable     = conversionfolder
        outputfolder        = '{output}'
    output:
        combinedplates = '{output}/counttables_combined_ALL.tsv'
    script:
        'combinespreadplates.R'