# Snakemake Workflow for Module 5: When multiple plates are present, combining all plate count tables into a single normalized count table

# Include common settings
include: "../common.snakefile"

rule all:
    input:
        combinedplates = expand('{output}/combined_count_tables/counttables_combined_ALL.csv', output = output)

rule combine_plates:
    input:
        plates = expand('{tmpstore}/mapping/{fileprefix}/counts.tsv', tmpstore=tmpstore, fileprefix=fileprefixes),
        inputfolder = expand('{tmpstore}/mapping/', tmpstore=tmpstore),
        annotations = annotationfile,
        conversiontable = conversionfolder
    output:
        combinedplates = '{output}/combined_count_tables/counttables_combined_ALL.csv'
    params:
        outputfolder = '{output}/combined_count_tables',
        rpackagesfolders  = rpackagesfolders,
        samples = fileprefixes
    script:
        'scripts/combinespreadplates.R'