# Snakemake Workflow for Module 6: Running RaceID / StemID on normalized combined count tables

# Include common settings
include: "../common.snakefile"

rule all:
    input:
        stemraceidreport    = '{raceidoutputsbydate}/raceid3stemid2/RaceID3_StemID2_sample.html',
        clustercells        = '{raceidoutputsbydate}/raceid3stemid2/cell_clust.xlx',
        clustergenes        = '{raceidoutputsbydate}/raceid3stemid2/cell_clust_diff_genes_cl_*'

rule raceid_stemid:
    input:
        countscombined      = expand('{output}/combined_count_tables/counttables_combined_ALL.csv', output = output),
        conversiontable     = conversionfolder
    output:
        stemraceidreport    = '{raceidoutputsbydate}/RaceID3_StemID2_sample.html',
        clustercells        = '{raceidoutputsbydate}/cell_clust.xlx',
        clustergenes        = '{raceidoutputsbydate}/cell_clust_diff_genes_cl_*'
    params:
        outputdirectory     = '{raceidoutputsbydate}/raceid3stemid2',
        mintotal            = mintotal,
        minexpr             = minexpr,
        minnumber           = minnumber,
        LBatch              = LBatch,
        CGenes              = CGenes,
        FGenes              = FGenes,
        ccor                = ccor,
        maxclustnr          = maxclustnr,
        bootnr              = bootnr,
        RunStemID           = RunStemID,
        pdishuf             = pdishuf,
        scthr               = scthr
    script:
        'RaceID2_StemID_render.R'