# Snakemake Workflow for Module 6: Running RaceID / StemID on normalized combined count tables

# Include common settings
include: "../common.snakefile"

rule raceid-stemid:
    input:
        countscombined = '{output}/combine_plates/{reference}/{fileprefix}/counttables_combined.tsv'
    output:
        stemraceidreport = '{output}/RaceID2_StemID_results.html'
        clustercells = '{output}/cell_clust.xlx'
        clustergenes = '{output}/cell_clust_diff_genes_cl_*'
    script:
        'RaceID2_StemID_sample.R'