# Snakemake Workflow for Module 4: Spread Counts

# Include common settings
include: "../common.snakefile"

rule combine-plates:
    input:
        plates = '{tmpstore}/quality_filters/{fileprefix}/counts_filtered_*.tsv'
    output:
        combinedplates = '{tmpstore}/counts/{fileprefix}.tsv'
    script:
        'spread-counts.R'