# Snakemake Workflow for Module 5: When multiple plates are present, combining all plate count tables into a single normalized count table

# Include common settings
include: "../common.snakefile"

rule combine-plates:
    input:
        plates = '{tmpstore}/quality_filters/{fileprefix}/counts_filtered_*.tsv'
    output:
        combinedplates = '{output}/counttables_combined.tsv'
    script:
        'combine-plates.R'