# Snakemake Workflow for Module 4: Using different types of filters to do quality checks on each plate

# Include common settings
include: "../common.snakefile"

rule qualitychecks:
    input:
        '{tmpstore}/mapping/{reference}/{fileprefix}/counts.tsv'
    output:
        temporary('{tmpstore}/quality_filters/{reference}/{fileprefix}/counts_filtered.tsv')
    script:
        'filter.R'