# #######################################
# Build from minimal Debian Jessie image 
#
# Use the docker CMD which is 'bash' 
# for this container
# #######################################

Bootstrap: docker
From: debian:8.11-slim
IncludeCmd: yes

%help
    This container provides STAR, pigz and featureCounts
    Run them with 
    'singularity run <containername> <program name> <arguments>'

%labels
    MAINTAINER d.molenaar@vu.nl

%post
    # #######################################
    # General
    # #######################################
    # Define the installation directory for 
    # executables 
    BIN=/usr/local/bin
    apt-get update

    # #######################################
    # Install pigz, the parallel implementa-
    # tion of gzip
    # #######################################
    apt-get -y install pigz

    # #######################################
    # Install STAR
    # #######################################
    VER=2.6.1d
    apt-get -y install make 
    apt-get -y install gcc zlib1g-dev g++ cmake
    apt-get -y install wget
    URL=https://github.com/alexdobin/STAR/archive/${VER}.tar.gz
    wget ${URL}
    tar -xzf ${VER}.tar.gz
    cd STAR-${VER}/source
    make CXXFLAGSextra=-march=native STAR && make CXXFLAGSextra=-march=native STARlong
    cp STAR ${BIN} && cp STARlong ${BIN}
    cd / && rm -r STAR-${VER} && rm ${VER}.tar.gz
    
    # #######################################
    # Install the Subread package
    # Subread provides the featureCounts pro-
    # gram
    # http://subread.sourceforge.net/
    # #######################################
    apt-get -y install make 
    apt-get -y install gcc zlib1g-dev 
    apt-get -y install wget
    VER=1.6.3
    URL=https://sourceforge.net/projects/subread/files/subread-${VER}/subread-${VER}-source.tar.gz
    wget ${URL}
    tar -xvzf subread-${VER}-source.tar.gz
    cd subread-${VER}-source/src
    make -f Makefile.Linux
    cp ../bin/utilities/* ${BIN}
    rm -rf ../bin/utilities
    cp ../bin/* ${BIN}
    cd / && rm -rf subread-${VER}-source && rm subread-${VER}-source.tar.gz
