$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

properties:
  datadir:
    type: string
  refdir:
    type: string
  indexdir: 
    type: string
  repo: 
    type: string
  tmpstore:
    type: string
  output: 
    type: string
  sequences:
    type: string
  samples:
    type: string
  references:
    type: string
  celbc:
    type: string
  rpackagesfolders:
    type: array
    items:
      type: string
  reference:
    type: string
  # samplescolumn:
  #  type: string
  annotationformat:
    type: string
    enum: ['gtf','gff']
  conversiontables:
    type: string
  filesuffix:
    type: object
    properties:
      align:
        type: array
        items:
          type: string
      barcodes:
        type: array
        items:
          type: string
    required:
      - align
      - barcodes
  istest:
    type: boolean
  testset:
    type: array
    items:
      type: string
  params:
    type: object
    properties:
      starindex:
        type: object
        properties:
          gtf:
            type: array
            items:
              type: string
          gff:
            type: array
            items:
              type: string
        required:
          - gtf
          - gff
      star:
        type: array
        items:
          type: string
      featureCounts:
        type: array
        items:
          type: string
    required:
      - starindex
      - star
      - featureCounts
  UMIcorrection:
    type: boolean
  UMIcardinality:
    type: integer
required:
  - datadir
  - refdir
  - indexdir
  - repo
  - tmpstore
  - output
  - sequences
  - samples
  - references
  - celbc
  - rpackagesfolders
  - reference
  - samplescolumn
  - annotationformat
  - conversiontables
  - filesuffix
  - istest
  - params
  - UMIcorrection

